python/django/saleor/saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.product_detail, name='product-detail'),
    url(r'^(?P<pk>[0-9]+)/publish/$', views.product_toggle_is_published,
        name='product-publish'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',
        views.product_create, name='product-add'),
    url(r'^bulk-update/$',
        views.product_bulk_update, name='product-bulk-update'),
    url(r'^add/select-type/$',
        views.product_select_type, name='product-add-select-type'),

    url(r'^types/$',
        views.product_type_list, name='product-type-list'),
    url(r'^types/add/$',
        views.product_type_create, name='product-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$',
        views.product_type_edit, name='product-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$',
        views.product_type_delete, name='product-type-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_add, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/add/$',
        views.stock_add, name='variant-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/$',
        views.stock_details, name='variant-stock-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/update/$',
        views.stock_edit, name='variant-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='variant-stock-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/$', views.product_images,
        name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_add, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_product_images, name='product-images-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_detail, name='product-attribute-detail'),
    url(r'attributes/add/$',
        views.attribute_add, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$',
        views.attribute_choice_value_add,
        name='product-attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$',  # noqa
        views.attribute_choice_value_edit,
        name='product-attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',  # noqa
        views.attribute_choice_value_delete,
        name='product-attribute-value-delete'),

    url(r'stocklocations/$', views.stock_location_list,
        name='product-stock-location-list'),
    url(r'stocklocations/add/$', views.stock_location_add,
        name='product-stock-location-add'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/$', views.stock_location_edit,
        name='product-stock-location-edit'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/delete/$',
        views.stock_location_delete, name='product-stock-location-delete'),

    url(r'^ajax/variants/$',
        views.ajax_available_variants_list, name='ajax-available-variants'),
    url(r'^ajax/products/$',
        views.ajax_products_list, name='ajax-products')]

python/django/saleor/saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name="add-to-cart"),
    url(r'^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$',
        views.collection_index, name='collection')]

python/django/saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from graphene_django.views import GraphQLView

from .account.urls import urlpatterns as account_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG), name='api'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social'))]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/django/saleor/saleor/dashboard/product/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, reverse
from django.template.response import TemplateResponse
from django.utils.translation import npgettext_lazy, pgettext_lazy
from django.views.decorators.http import require_POST
from django_prices.templatetags.prices_i18n import gross

from . import forms
from ...core.utils import get_paginator_items
from ...product.models import (
    AttributeChoiceValue, Product, ProductAttribute, ProductImage, ProductType,
    ProductVariant, Stock, StockLocation)
from ...product.utils import (
    get_availability, get_product_costs_data, get_variant_costs_data)
from ..views import staff_member_required
from .filters import (
    ProductAttributeFilter, ProductFilter, ProductTypeFilter,
    StockLocationFilter)


@staff_member_required
@permission_required('product.view_properties')
def product_type_list(request):
    types = ProductType.objects.all().prefetch_related(
        'product_attributes', 'variant_attributes').order_by('name')
    type_filter = ProductTypeFilter(request.GET, queryset=types)
    form = forms.ProductTypeForm(request.POST or None)
    if form.is_valid():
        return redirect('dashboard:product-type-add')
    types = get_paginator_items(
        type_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    types.object_list = [
        (pc.pk, pc.name, pc.has_variants, pc.product_attributes.all(),
         pc.variant_attributes.all())
        for pc in types.object_list]
    ctx = {
        'form': form, 'product_types': types, 'filter_set': type_filter,
        'is_empty': not type_filter.queryset.exists()}
    return TemplateResponse(
        request,
        'dashboard/product/product_type/list.html',
        ctx)


@staff_member_required
@permission_required('product.edit_properties')
def product_type_create(request):
    product_type = ProductType()
    form = forms.ProductTypeForm(
        request.POST or None, instance=product_type)
    if form.is_valid():
        product_type = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product type %s') % (product_type,)
        messages.success(request, msg)
        return redirect('dashboard:product-type-list')
    ctx = {'form': form, 'product_type': product_type}
    return TemplateResponse(
        request,
        'dashboard/product/product_type/form.html',
        ctx)


@staff_member_required
@permission_required('product.edit_properties')
def product_type_edit(request, pk):
    product_type = get_object_or_404(ProductType, pk=pk)
    form = forms.ProductTypeForm(
        request.POST or None, instance=product_type)
    if form.is_valid():
        product_type = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product type %s') % (product_type,)
        messages.success(request, msg)
        return redirect('dashboard:product-type-update', pk=pk)
    ctx = {'form': form, 'product_type': product_type}
    return TemplateResponse(
        request,
        'dashboard/product/product_type/form.html',
        ctx)


@staff_member_required
@permission_required('product.edit_properties')
def product_type_delete(request, pk):
    product_type = get_object_or_404(ProductType, pk=pk)
    if request.method == 'POST':
        product_type.delete()
        msg = pgettext_lazy(
            'Dashboard message', 'Removed product type %s') % (product_type,)
        messages.success(request, msg)
        return redirect('dashboard:product-type-list')
    ctx = {
        'product_type': product_type,
        'products': product_type.products.all()}
    return TemplateResponse(
        request,
        'dashboard/product/product_type/modal/confirm_delete.html',
        ctx)


@staff_member_required
@permission_required('product.view_product')
def product_list(request):
    products = Product.objects.prefetch_related('images')
    products = products.order_by('name')
    product_types = ProductType.objects.all()
    product_filter = ProductFilter(request.GET, queryset=products)
    products = get_paginator_items(
        product_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'bulk_action_form': forms.ProductBulkUpdate(),
        'products': products, 'product_types': product_types,
        'filter_set': product_filter,
        'is_empty': not product_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/product/list.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_select_type(request):
    """View for add product modal embedded in the product list view."""
    form = forms.ProductTypeSelectorForm(request.POST or None)
    status = 200
    if form.is_valid():
        redirect_url = reverse(
            'dashboard:product-add',
            kwargs={'type_pk': form.cleaned_data.get('product_type').pk})
        return (
            JsonResponse({'redirectUrl': redirect_url})
            if request.is_ajax() else redirect(redirect_url))
    elif form.errors:
        status = 400
    ctx = {'form': form}
    template = 'dashboard/product/modal/select_type.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.edit_product')
def product_create(request, type_pk):
    product_type = get_object_or_404(ProductType, pk=type_pk)
    create_variant = not product_type.has_variants
    product = Product()
    product.product_type = product_type
    product_form = forms.ProductForm(request.POST or None, instance=product)
    if create_variant:
        variant = ProductVariant(product=product)
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if product_form.is_valid() and not variant_errors:
        product = product_form.save()
        if create_variant:
            variant.product = product
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-detail', pk=product.pk)
    ctx = {
        'product_form': product_form, 'variant_form': variant_form,
        'product': product}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.view_product')
def product_detail(request, pk):
    products = Product.objects.prefetch_related(
        'variants__stock', 'images',
        'product_type__variant_attributes__values').all()
    product = get_object_or_404(products, pk=pk)
    variants = product.variants.all()
    images = product.images.all()
    availability = get_availability(product)
    sale_price = availability.price_range
    purchase_cost, gross_margin = get_product_costs_data(product)
    gross_price_range = product.get_gross_price_range()

    # no_variants is True for product types that doesn't require variant.
    # In this case we're using the first variant under the hood to allow stock
    # management.
    no_variants = not product.product_type.has_variants
    only_variant = variants.first() if no_variants else None
    stock = only_variant.stock.all() if only_variant else Stock.objects.none()
    ctx = {
        'product': product, 'sale_price': sale_price, 'variants': variants,
        'gross_price_range': gross_price_range, 'images': images,
        'no_variants': no_variants, 'only_variant': only_variant,
        'stock': stock, 'purchase_cost': purchase_cost,
        'gross_margin': gross_margin, 'is_empty': not variants.exists()}
    return TemplateResponse(request, 'dashboard/product/detail.html', ctx)


@require_POST
@staff_member_required
@permission_required('product.edit_product')
def product_toggle_is_published(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_published = not product.is_published
    product.save(update_fields=['is_published'])
    return JsonResponse(
        {'success': True, 'is_published': product.is_published})


@staff_member_required
@permission_required('product.edit_product')
def product_edit(request, pk):
    product = get_object_or_404(
        Product.objects.prefetch_related('variants'), pk=pk)

    edit_variant = not product.product_type.has_variants
    form = forms.ProductForm(request.POST or None, instance=product)

    if edit_variant:
        variant = product.variants.first()
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if form.is_valid() and not variant_errors:
        product = form.save()
        if edit_variant:
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-detail', pk=product.pk)
    ctx = {
        'product': product, 'product_form': form, 'variant_form': variant_form}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        msg = pgettext_lazy(
            'Dashboard message', 'Removed product %s') % (product,)
        messages.success(request, msg)
        return redirect('dashboard:product-list')
    return TemplateResponse(
        request,

python/django/saleor/templates/dashboard/product/product_variant/_image_select.html
{% load i18n %}

<div class="image_select">
  <div class="row">
    {% for choice_with_image in choices_with_images %}
      {% with choice=choice_with_image.0 image=choice_with_image.1 %}
        <div class="image_select-item">
          <input id="{{ choice.id_for_label }}" name="{{ choice.data.name }}" class="filled-in" type="checkbox" value="{{ choice.data.value }}" {% if choice.data.selected %}checked{% endif %}>
          <label for="{{ choice.id_for_label }}"></label>
          <img id="{{ choice.id_for_label }}" class="responsive-img" src="{{ image.image.crop.200x200 }}" srcset="{{ image.image.crop.200x200 }} 1x" alt="">
          <div id="{{ choice.id_for_label }}" class="image_select-item-overlay{% if choice.data.selected %} checked{% endif %}"></div>
        </div>
      {% endwith %}
    {% endfor %}
  </div>
  {% for error in field.errors %}
    <p class="help-block materialize-red-text">{{ error }}</p>
  {% endfor %}
  {% if field.help_text %}
    <p class="help-block">{{ field.help_text|safe }}</p>
  {% endif %}
</div>

python/django/saleor/templates/dashboard/product/product_variant/detail.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load prices_i18n %}
{% load staticfiles %}
{% load status %}

{% block title %}
  {{ variant }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Product form breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li class="hide-on-med-and-down">
      <a href="{% url "dashboard:product-detail" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ variant }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <div class="card-content">
          <p class="card-title">{{ product }} <br> {% trans "SKU" context "Dashboard variant details view" %} {{ variant.sku }}</p>
          <p></p>
          <div class="row">
            <div class="col s5 m6">
              <p class="text-padding">{% trans "Sale price" context "Dashboard variant details view" %}</p>
            </div>
            <div class="col s7 m6">
              <p class="text-padding right-align">{% gross variant.get_price_per_item %}</p>
            </div>
            <div class="col s5 m6">
              <p class="text-padding">{% trans "Cost price range" context "Dashboard variant details view" %}</p>
            </div>
            <div class="col s7 m6">
              <p class="text-padding right-align">
                {% if costs|length > 1 %}
                  {% gross costs|first %} - {% gross costs|last %}
                {% elif costs|length == 1 %}
                  {% gross costs|first %}
                {% else %}
                  -
                {% endif %}
              </p>
            </div>
            <div class="col s5 m6">
              <p class="text-padding">{% trans "Gross margin" context "Dashboard variant details view" %}</p>
            </div>
            <div class="col s7 m6">
              <p class="text-padding right-align">
                {% if margins|length > 1 %}
                  {{ margins|first }}% - {{ margins|last }}%
                {% else %}
                  {% if margins %}
                    {{ margins|first }}% - {{ margins|last }}%
                  {% else %}
                    -
                  {% endif %}
                {% endif %}
              </p>
            </div>
          </div>
        </div>
        {% if perms.product.edit_product %}
          <div class="card-action">
            <a class="btn-flat waves-effect" href="{% url 'dashboard:variant-update' product_pk=product.pk variant_pk=variant.pk %}">
              {% trans "Edit variant" context "Dashboard action" %}
            </a>
            <a href="#base-modal" class="btn-flat waves-effect modal-trigger-custom" data-href="{% url 'dashboard:variant-delete' product_pk=product.pk variant_pk=variant.pk %}">
              {% trans "Remove variant" context "Dashboard action" %}
            </a>
          </div>
        {% endif %}
      </div>
      {% if perms.product.view_stock_location %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">{% trans "Stock" context "Dashboard variant details view" %}</span>
          </div>
          {% if perms.product.edit_stock_location %}
            <div class="data-table-header-action">
              <a class="btn-flat waves-effect" href="{% url "dashboard:variant-stock-add" product_pk=product.pk variant_pk=variant.pk %}">
                {% trans "Add" context "Dashboard action" %}
              </a>
            </div>
          {% endif %}
          <div class="data-table-container">
            {% include "dashboard/product/_stock_table.html" with product=product variant=variant stock=stock %}
          </div>
        </div>
      {% endif %}
    </div>
    <div class="col m12 l3">
      <div class="card">
        <div class="card-content">
          <h5>{% render_variant_availability_status variant %}</h5>
        </div>
      </div>
      <div class="card">
        <div class="card-content">
          <span class="card-title">{% trans "Images" context "Dashboard variant details view" %}</span>
          <p>
            {% for image in images %}
              <img class="responsive-img" src="{{ image.image.crop.60x60 }}" srcset="{{ image.image.crop.60x60 }} 1x" alt="">
            {% empty %}
              {% trans "No images" %}
            {% endfor %}
          </p>
        </div>
        {% if perms.product.edit_product %}
          <div class="card-action">
            <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:variant-images' product_pk=product.pk variant_pk=variant.pk %}">
              {% trans "Select images" context "Dashboard action" %}
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

python/django/saleor/templates/dashboard/product/product_variant/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% if variant.pk %}
    {% trans "Edit" context "Variant form page title" %} - {{ variant }}
  {% else %}
    {% trans "Add variant" context "Variant form page title" %}
  {% endif %}
   - {{ block.super }}
{% endblock %}

{% block body_class %}body-store body-products{% endblock %}

{% block header_menu %}
  {% url "dashboard:variant-details" product_pk=product.pk variant_pk=variant.pk as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Dashboard products list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-detail" pk=product.pk %}">
        <svg data-src="{% static "dashboard/images/chevron-left.svg" %}" />
      </a>
    </li>
    <li>
      <a href="{% url "dashboard:product-detail" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    {% if variant.pk %}
      <li>
        <a href="{% url "dashboard:variant-details" product_pk=product.pk variant_pk=variant.pk %}" class="breadcrumbs--ellipsed-item">
          {{ variant }}
        </a>
      </li>
      <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "Variant form breadcrumbs" %}
      </span>
    </li>
    {% else %}
      <li>
        <span class="hide-on-med-and-down">
          {% trans "Add variant" context "Variant form breadcrumbs" %}
        </span>
        <span class="hide-on-large-only breadcrumbs--ellipsed-item">
          {% blocktrans trimmed context "Variant form breadcrumbs" %}
            Add variant for {{ product }}
          {% endblocktrans %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <form method="post" id="form-variant" enctype="multipart/form-data">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              <div class="col s12 m8">
                <div class="row">
                  {{ form.name|materializecss }}
                </div>
                {% if attribute_form.fields %}
                  {% for attribute_field in attribute_form %}
                    <div class="row">
                      {{ attribute_field|materializecss }}
                    </div>
                  {% endfor %}
                {% else %}
                  <p>
                    {% trans "This product has no attributes." context "Variant form text" %}
                  </p>
                {% endif %}
              </div>
              <div class="col s12 m4">
                <div class="row">
                  {{ form.sku|materializecss }}
                </div>
                <div class="row">
                  {{ form.price_override|materializecss }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            {% if variant.pk %}
              <a href="{% url "dashboard:variant-details" product_pk=product.pk variant_pk=variant.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url "dashboard:product-detail" pk=product.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3 help-box"></div>
  </div>
{% endblock %}