python/django/saleor/saleor/dashboard/group/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.group_list, name='group-list'),
    url(r'^group-create/$', views.group_create, name='group-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.group_details, name='group-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.group_delete, name='group-delete')]

python/django/saleor/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change-stock/$',
        views.orderline_change_stock, name='orderline-change-stock'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/add-variant/$',
        views.add_variant_to_group, name='add-variant-to-group'),
    url(r'^(?P<order_pk>\d+)/invoice/$',
        views.order_invoice, name='order-invoice'),
    url(r'^(?P<group_pk>\d+)/packing-slips/$',
        views.order_packing_slip, name='order-packing-slips')]

python/django/saleor/saleor/dashboard/shipping/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.shipping_method_list, name='shipping-methods'),
    url(r'^add/$', views.shipping_method_add, name='shipping-method-add'),
    url(r'^(?P<pk>\d+)/update/$', views.shipping_method_edit,
        name='shipping-method-update'),
    url(r'^(?P<pk>\d+)/$', views.shipping_method_detail,
        name='shipping-method-detail'),
    url(r'^(?P<pk>\d+)/delete/$',
        views.shipping_method_delete, name='shipping-method-delete'),

    url(r'^(?P<shipping_method_pk>\d+)/country/add/$',
        views.shipping_method_country_add,
        name='shipping-method-country-add'),
    url(r'^(?P<shipping_method_pk>\d+)/country/(?P<country_pk>\d+)/update/$',
        views.shipping_method_country_edit,
        name='shipping-method-country-edit'),
    url(r'^(?P<shipping_method_pk>\d+)/country/(?P<country_pk>\d+)/delete/$',
        views.shipping_method_country_delete,
        name='shipping-method-country-delete'),
]

python/django/saleor/saleor/dashboard/urls.py
from django.conf import settings
from django.conf.urls import include, url
from graphene_django.views import GraphQLView

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .graphql.api import schema
from .group.urls import urlpatterns as groups_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^collections/', include(collection_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^graphql/', GraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG), name='api'),
    url(r'^groups/', include(groups_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
    url(r'^search/', include(search_urls)),
]

python/django/saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from graphene_django.views import GraphQLView

from .account.urls import urlpatterns as account_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG), name='api'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social'))]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/django/saleor/saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils.translation import pgettext_lazy
from text_unidecode import unidecode

from ...product.models import Category


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super(CategoryForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Category
        exclude = ['slug']
        labels = {
            'name': pgettext_lazy(
                'Item name',
                'Name'),
            'description': pgettext_lazy(
                'Description',
                'Description')}

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))
        if self.parent_pk:
            self.instance.parent = get_object_or_404(
                Category, pk=self.parent_pk)
        return super().save(commit=commit)

python/django/saleor/saleor/dashboard/customer/forms.py
from django import forms

from ...account.models import User


class CustomerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        # disable 'is_active' checkbox if user edits his own account
        if self.user == self.instance:
            self.fields['is_active'].disabled = True

    class Meta:
        model = User
        fields = ['email', 'is_active']

python/django/saleor/saleor/dashboard/search/forms.py
from ...search.backends import picker
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):
    def search(self):
        query = self.cleaned_data['q']
        search = picker.pick_dashboard_backend()
        return search(query)

python/django/saleor/saleor/checkout/views/shipping.py
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from ...account.forms import get_address_form
from ...account.models import Address
from ..forms import AnonymousUserShippingForm, ShippingAddressesForm


def anonymous_user_shipping_address_view(request, checkout):
    """Display the shipping step for a user who is not logged in."""
    address_form, preview = get_address_form(
        request.POST or None, country_code=request.country.code,
        autocomplete_type='shipping',
        initial={'country': request.country.code},
        instance=checkout.shipping_address)

    user_form = AnonymousUserShippingForm(
        not preview and request.POST or None, initial={'email': checkout.email}
        if not preview else request.POST.dict())
    if all([user_form.is_valid(), address_form.is_valid()]):
        checkout.shipping_address = address_form.instance
        checkout.email = user_form.cleaned_data['email']
        return redirect('checkout:shipping-method')
    return TemplateResponse(
        request, 'checkout/shipping_address.html', context={
            'address_form': address_form, 'user_form': user_form,
            'checkout': checkout})


def user_shipping_address_view(request, checkout):
    """Display the shipping step for a logged in user.

    In addition to entering a new address the user has an option of selecting
    one of the existing entries from their address book.
    """
    data = request.POST or None
    additional_addresses = request.user.addresses.all()
    checkout.email = request.user.email
    shipping_address = checkout.shipping_address

    if shipping_address is not None and shipping_address.id:
        address_form, preview = get_address_form(
            data, country_code=request.country.code,
            initial={'country': request.country})
        addresses_form = ShippingAddressesForm(
            data, additional_addresses=additional_addresses,
            initial={'address': shipping_address.id})
    elif shipping_address:
        address_form, preview = get_address_form(
            data, country_code=shipping_address.country.code,
            instance=shipping_address)
        addresses_form = ShippingAddressesForm(
            data, additional_addresses=additional_addresses)
    else:
        address_form, preview = get_address_form(
            data, initial={'country': request.country},
            country_code=request.country.code)
        addresses_form = ShippingAddressesForm(
            data, additional_addresses=additional_addresses)

    if addresses_form.is_valid() and not preview:
        if (addresses_form.cleaned_data['address'] !=
                ShippingAddressesForm.NEW_ADDRESS):
            address_id = addresses_form.cleaned_data['address']
            checkout.shipping_address = Address.objects.get(id=address_id)
            return redirect('checkout:shipping-method')
        elif address_form.is_valid():
            checkout.shipping_address = address_form.instance
            return redirect('checkout:shipping-method')
    return TemplateResponse(
        request, 'checkout/shipping_address.html', context={
            'address_form': address_form, 'user_form': addresses_form,
            'checkout': checkout,
            'additional_addresses': additional_addresses})

python/django/saleor/saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'categories': categories, 'filter_set': category_filter,
        'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.view_category')
def category_detail(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root,
           'filter_set': category_filter,
           'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-detail', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-detail', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

python/django/saleor/templates/dashboard/shipping/detail.html
{% extends 'dashboard/base.html' %}

{% load i18n %}
{% load prices_i18n %}
{% load staticfiles %}

{% block title %}
    {{ shipping_method }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-shipping-methods{% endblock %}

{% block menu_delivery_class %}active{% endblock %}

{% block menu_shipping_class %} active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:shipping-methods' %}">
        {% trans "Shipping methods" context "Shipping method form breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:shipping-methods' %}"><i class="material-icons">arrow_back</i></a>
    </li>
    <li>
      <span class="breadcrumbs--elipsed-item">
        {{ shipping_method }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ shipping_method.name }}
          </span>
          <div class="row">
            {% if shipping_method.description %}
              <div class="col s12 m4 l12">
                <h4>
                  {% trans "Description" context "Shipping method field" %}
                </h4>
                <p>
                  {{ shipping_method.description }}
                </p>
              </div>
            {% endif %}
          </div>
        </div>
        {% if perms.shipping.edit_shipping %}
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url 'dashboard:shipping-method-update' shipping_method.pk %}">
            {% trans "Edit shipping method" context "Shipping method action" %}
          </a>
          <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:shipping-method-delete' shipping_method.pk %}">
            {% trans "Remove shipping method" context "Shipping method action" %}
          </a>
        </div>
        {% endif %}
      </div>
    </div>

    <div class="col m12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
             {% trans "Price per country" context "Title of the per-country shipping price list" %}
          </span>
        </div>
        <div class="data-table-header-action">
            <a href="{% url 'dashboard:shipping-method-country-add' shipping_method_pk=shipping_method.pk %}" class="btn-data-table btn-flat waves-effect">
              {% trans "Add" %}
            </a>
        </div>
        <div class="data-table-container">
          <table class="bordered highlight responsive data-table">
            <thead>
              <tr>
                <th>
                  {% trans "Country" context "Header of the per-country shipping price list" %}
                </th>
                <th>
                  {% trans "Price" context "Header of the per-country shipping price list" %}
                </th>
              </tr>
            </thead>
            <tbody>
              {% for country in method_countries %}
                <tr>
                  <td>{{ country.get_country_code_display }}</td>
                  <td>{% gross country.price %}</td>
                  <td class="right-align">
                    <a href="{% url 'dashboard:shipping-method-country-edit' shipping_method_pk=shipping_method.pk country_pk=country.pk %}" class="btn-flat waves-effect">
                      {% trans 'Edit' context 'Attribute choice value edit action' %}
                    </a>
                    <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:shipping-method-country-delete' shipping_method_pk=shipping_method.pk country_pk=country.pk %}">
                      {% trans 'Remove' context 'Attribute choice value remove action' %}
                    </a>
                  </td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="2">{% trans "No shipping prices" context "Empty list of per-country shipping prices" %}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

python/django/saleor/templates/dashboard/shipping/form.html
{% extends "dashboard/base.html" %}
{% load materializecss %}
{% load i18n %}
{% load mptt_tags %}
{% load staticfiles %}

{% block title %}
  {% if shipping_method.pk %}
    {% trans "Edit" context "Dashboard shipping methods" %}
    - {{ shipping_method }}
  {% else %}
    {% trans "Add new method" context "Shipping method form page title" %}
  {% endif %}
  - {{ block.super }}
{% endblock %}

{% block body_class %}body-shipping-methods{% endblock %}

{% block menu_delivery_class %}active{% endblock %}

{% block page_title %}
  {% if shipping_method.pk %}
    {{ shipping_method }}
  {% else %}
    {% trans "Add new method" context "Shipping method form page title" %}
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:shipping-methods' %}">
        {% trans "Shipping methods" context "Dashboard shipping method" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:shipping-methods' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if shipping_method.pk %}
    <li>
      <a href="{% url 'dashboard:shipping-method-detail' shipping_method.pk %}" class="breadcrumbs--ellipsed-item">
        {{ shipping_method }}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "Shipping method form page title" %}
      </span>
    </li>
    {% else %}
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Add new method" context "Shipping method form breadcrumbs" %}
      </span>
    </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_shipping_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <form method="post" id="form-method">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              {{ form|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            {% if shipping_method.pk %}
              <a href="{% url 'dashboard:shipping-method-detail' shipping_method.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:shipping-methods' %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 l3 help-box"></div>
  </div>
{% endblock %}

python/django/saleor/templates/dashboard/shipping/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load status %}
{% load utils %}
{% load static %}

{% block title %}
  {% trans "Shipping methods" context "Dashboard shipping methods list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-shipping-methods{% endblock %}

{% block menu_delivery_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Shipping methods" context "Dashboard shipping methods list" %}
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
  {% if perms.shipping.edit_shipping %}
  <div class="btn-fab-fixed">
    <a href="{% url 'dashboard:shipping-method-add' %}" class="btn-fab-default waves-effect waves-light" title="{% trans "Add method" context "Shipping method list add button text" %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if shipping_methods %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  {% trans "Name" context "Shipping methods table header" as label %}
                  {% sorting_header 'name' label is_wide=True %}

                  <th>
                    {% trans "Price range" context "Shipping methods table header" %}
                  </th>
                  <th class="wide">
                    {% trans "Countries" context "Shipping methods table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for method in shipping_methods %}
                  <tr data-action-go="{% if perms.shipping.edit_shipping %}{% url 'dashboard:shipping-method-detail' pk=method.pk %}{% endif %}">
                    <td>
                      {{ method }}
                    </td>
                    <td>
                      {% if not method.price_range %}
                        -
                      {% elif method.price_range.min_price == method.price_range.max_price %}
                        {% gross method.price_range.min_price html=True %}
                      {% else %}
                        {% gross method.price_range.min_price html=True %}&ndash;{% gross method.price_range.max_price html=True %}
                      {% endif %}
                    </td>
                    <td>
                      {{ method.countries|join:", " }}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% paginate shipping_methods %}
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/shipping/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No shipping methods found." context "Empty shipping list message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
  </div>
{% endblock %}

python/django/saleor/templates/dashboard/shipping/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No shipping methods found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Shipping methods allows defining shipping methods that are available in the shop.<br>
    You can add shipping methods by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}" /></span> button.
  {% endblocktrans %}
{% endblock %}