python/django/saleor/saleor/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^$', views.details, name='details'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^password/reset/$', views.password_reset,
        name='reset-password'),
    url(r'^password/reset/done/$', django_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'),
        name='reset-password-done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',  # noqa
        views.password_reset_confirm, name='reset-password-confirm'),
    url(r'password/reset/complete/$', django_views.PasswordResetCompleteView.as_view(  # noqa
        template_name='account/password_reset_from_key_done.html'),
        name='reset-password-complete'),

    url(r'^address/(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^address/(?P<pk>\d+)/delete/$',
        views.address_delete, name='address-delete'),
]

python/django/saleor/saleor/dashboard/group/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.group_list, name='group-list'),
    url(r'^group-create/$', views.group_create, name='group-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.group_details, name='group-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.group_delete, name='group-delete')]

python/django/saleor/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change-stock/$',
        views.orderline_change_stock, name='orderline-change-stock'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/add-variant/$',
        views.add_variant_to_group, name='add-variant-to-group'),
    url(r'^(?P<order_pk>\d+)/invoice/$',
        views.order_invoice, name='order-invoice'),
    url(r'^(?P<group_pk>\d+)/packing-slips/$',
        views.order_packing_slip, name='order-packing-slips')]

python/django/saleor/saleor/dashboard/sites/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='site-index'),
    url(r'^(?P<pk>\d+)/update/$', views.site_settings_edit,
        name='site-update'),
    url(r'^(?P<pk>\d+)/$', views.site_settings_detail,
        name='site-detail'),
    url(r'^(?P<pk>\d+)/delete/$', views.site_settings_edit,
        name='site-delete'),

    url(r'^(?P<site_settings_pk>\d+)/authorization_key/add/$',
        views.authorization_key_add, name='authorization-key-add'),
    url(r'^(?P<site_settings_pk>\d+)/authorization_key/'
        r'(?P<key_pk>\d+)/update/$',
        views.authorization_key_edit, name='authorization-key-edit'),
    url(r'^(?P<site_settings_pk>\d+)/authorization_key/'
        r'(?P<key_pk>\d+)/delete/$',
        views.authorization_key_delete, name='authorization-key-delete')]

python/django/saleor/saleor/dashboard/staff/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.staff_list, name='staff-list'),
    url(r'^staff-create/$', views.staff_create, name='staff-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.staff_details, name='staff-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.staff_delete, name='staff-delete')]

python/django/saleor/saleor/dashboard/urls.py
from django.conf import settings
from django.conf.urls import include, url
from graphene_django.views import GraphQLView

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .graphql.api import schema
from .group.urls import urlpatterns as groups_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^collections/', include(collection_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^graphql/', GraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG), name='api'),
    url(r'^groups/', include(groups_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
    url(r'^search/', include(search_urls)),
]

python/django/saleor/saleor/search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search')]

python/django/saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from graphene_django.views import GraphQLView

from .account.urls import urlpatterns as account_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(
        schema=schema, graphiql=settings.DEBUG), name='api'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social'))]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/django/saleor/saleor/dashboard/customer/forms.py
from django import forms

from ...account.models import User


class CustomerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        # disable 'is_active' checkbox if user edits his own account
        if self.user == self.instance:
            self.fields['is_active'].disabled = True

    class Meta:
        model = User
        fields = ['email', 'is_active']

python/django/saleor/saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'categories': categories, 'filter_set': category_filter,
        'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.view_category')
def category_detail(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root,
           'filter_set': category_filter,
           'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-detail', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-detail', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

python/django/saleor/saleor/dashboard/collection/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Collection
from ..views import staff_member_required
from .filters import CollectionFilter
from .forms import CollectionForm


@staff_member_required
@permission_required('product.view_product')
def collection_list(request):
    collections = Collection.objects.prefetch_related('products').all()
    collection_filter = CollectionFilter(request.GET, queryset=collections)
    collections = get_paginator_items(
        collection_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'collections': collections, 'filter_set': collection_filter,
        'is_empty': not collection_filter.queryset.exists()}
    return TemplateResponse(
        request, 'dashboard/collection/list.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def collection_create(request):
    collection = Collection()
    form = CollectionForm(request.POST or None, instance=collection)
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy('Collection message', 'Added collection')
        messages.success(request, msg)
        return redirect('dashboard:collection-list')
    ctx = {'collection': collection, 'form': form}
    return TemplateResponse(request, 'dashboard/collection/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def collection_update(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    form = CollectionForm(request.POST or None, instance=collection)
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy('Collection message', 'Updated collection')
        messages.success(request, msg)
        return redirect('dashboard:collection-update', pk=collection.pk)
    ctx = {'collection': collection, 'form': form}
    return TemplateResponse(request, 'dashboard/collection/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def collection_delete(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    if request.method == 'POST':
        collection.delete()
        msg = pgettext_lazy('Collection message', 'Deleted collection')
        messages.success(request, msg)
        if request.is_ajax():
            response = {'redirectUrl': reverse('dashboard:collection-list')}
            return JsonResponse(response)
        return redirect('dashboard:collection-list')
    ctx = {'collection': collection}
    return TemplateResponse(
        request, 'dashboard/collection/confirm_delete.html', ctx)

python/django/saleor/templates/dashboard/base.html
<!DOCTYPE html>
{% load staticfiles i18n %}
{% load render_bundle from webpack_loader %}
{% load version %}
{% load serialize_messages from utils %}

<html lang="{{ LANGUAGE_CODE }}" class="no-js">
  <head>
    <title>
      {% block title %}
        {% trans "Dashboard - Saleor" context "Dashboard default page title" %}
      {% endblock %}
    </title>
    {% block meta %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
      <meta name="theme-color" content="#21915a" />
      <meta name="robots" content="noindex, nofollow">
    {% endblock meta %}

    {% include 'favicon.html' %}
    {% render_bundle 'vendor' 'css' %}
    {% render_bundle 'dashboard' 'css' %}
    <link rel="stylesheet" type="text/css" href="{% static "versatileimagefield/css/versatileimagefield.css" %}">

    {% block custom_css %}{% endblock %}
  </head>

  <body class="{% block body_class %}body-home{% endblock %}">
    <header>
      <nav class="top-nav" id="top-nav">
        <div class="nav-wrapper">
          <div class="right">
            <ul id="user-action" class="dropdown-content">
              <li class="user-name">
                {{ request.user }}
              </li>
              <li class="divider"></li>
              <li>
                <a href="{% url 'home' %}" target="_blank" class="waves-effect">
                  {% trans "Visit storefront" context "Dashboard top navigation action" %}
                </a>
              </li>
              <li>
                <a href="{% url "dashboard:styleguide" %}" target="_blank" class="waves-effect">
                  {% trans "Style guide" context "Dashboard top navigation action" %}
                </a>
              </li>
              <li>
                <a href="{% url 'account:logout' %}" class="waves-effect">
                  {% trans "Log out" context "Dashboard top navigation action" %}
                </a>
              </li>
            </ul>
            <a class="dropdown-button" data-constrainwidth="false" href="#" data-activates="user-action">
              <svg data-src="{% static "/dashboard/images/account-circle.svg" %}" width="24" height="24" fill="#fff" />
            </a>
            {% if SEARCH_IS_ENABLED %}
              <a href="{% url "dashboard:search" %}" class="dropdown-button hide-on-med-and-up" id="btn-search">
                <svg data-src="{% static "dashboard/images/search.svg" %}" width="24" height="24" fill="#fff" />
              </a>
            {% endif %}
          </div>
          <ul class="left">
            <li>
              <a href="#" id="toggle-menu">
                <svg data-src="{% static "dashboard/images/mobile-menu.svg" %}" width="24" height="24" />
              </a>
            </li>
            <li>
              <a href="{% url 'dashboard:index' %}" class="logo">
                <svg data-src="{% static "dashboard/images/logo.svg" %}" height="38px" width="176px" />
              </a>
            </li>
            <li class="search">
              {% if SEARCH_IS_ENABLED %}
                <form method="get" action="{% url "dashboard:search" %}">
                  <a class="hide-on-med-and-up" id="btn-search-close"></a>
                  <div class="input-field d-inline">
                    <input id="search" type="search" placeholder="{% trans "Search" context "Dashboard search" %}" name="q" required value="{% if query %}{{ query }}{% endif %}">
                    <label class="hide-on-small-only">
                      <svg data-src="{% static "dashboard/images/search.svg" %}" width="24" height="24" fill="#fff" />
                    </label>
                  </div>
                  <a href="{% url "dashboard:search" %}" class="hide-on-med-and-up" id="btn-search-submit">
                    <svg data-src="{% static "dashboard/images/search.svg" %}" width="24" height="24" fill="#fff" />
                  </a>
                </form>
              {% endif %}
            </li>
          </ul>
          <ul class="side-nav">
            <li class="nav-home">
              <a href="{% url 'dashboard:index' %}">
                {% trans "Home" context "Dashboard homepage" %}
              </a>
            </li>
            {% if perms.product.view_product or perms.product.view_category or perms.product.view_stock_location %}
            <li class="side-nav-section" id="first">
              <p>
                {% trans "Catalogue" context "Dashboard catalogue" %}
              </p>
              <ul>
                {% if perms.product.view_product %}
                  <li class="{% block menu_products_class %}{% endblock %}">
                    <a href="{% url 'dashboard:product-list' %}">
                      {% trans "Products" context "Dashboard products list" %}
                    </a>
                  </li>
                {% endif %}
                {% if perms.product.view_category %}
                  <li class="{% block menu_categories_class %}{% endblock %}">
                    <a href="{% url 'dashboard:category-list' %}">
                      {% trans "Categories" context "Dashboard categories list" %}
                    </a>
                  </li>
                {% endif %}
                {% if perms.product.view_stock_location %}
                  <li class="{% block menu_location_class %}{% endblock %}">
                    <a href="{% url 'dashboard:product-stock-location-list' %}">
                    {% trans "Stock locations" context "Dashboard stock loactions list" %}
                    </a>
                  </li>
                {% endif %}
                {% if perms.product.view_product %}
                <li class="{% block menu_collections_class %}{% endblock %}">
                  <a href="{% url 'dashboard:collection-list' %}">
                    {% trans "Collections" context "Dashboard side navigation link" %}
                  </a>
                </li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            {% if perms.discount.view_sale or perms.discount.view_voucher %}
            <li class="side-nav-section">
              <p>
                {% trans "Discounts" context "Dashboard discounts list" %}
              </p>
              <ul>
                {% if perms.discount.view_sale %}
                  <li class="{% block menu_sales_class %}{% endblock %}">
                    <a href="{% url 'dashboard:sale-list' %}">
                      {% trans "Sales" context "Dashboard sales (discounts) list" %}
                    </a>
                  </li>
                {% endif %}
                {% if perms.discount.view_voucher %}
                  <li class="{% block menu_vouchers_class %}{% endblock %}">
                    <a href="{% url 'dashboard:voucher-list' %}">
                      {% trans "Vouchers" context "Dashboard vouchers list" %}
                    </a>
                  </li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            {% if perms.order.view_order or perms.account.view_user %}
            <li class="side-nav-section">
              <p>
                {% trans "Sales" context "Dashboard sales. `Sales' is noun of to sell" %}
              </p>
              <ul>
                {% if perms.order.view_order %}
                  <li class="{% block menu_orders_class %}{% endblock %}">
                    <a href="{% url 'dashboard:orders' %}">
                      {% trans "Orders" context "Dashboard orders list" %}
                    </a>
                  </li>
                {% endif %}
                {% if perms.account.view_user %}
                  <li class="{% block menu_customers_class %}{% endblock %}">
                    <a href="{% url 'dashboard:customers' %}">
                      {% trans "Customers" context "Dashboard customers list" %}
                    </a>
                  </li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            {% if perms.account.view_group or perms.account.edit_group %}
              <li class="side-nav-section">
                <p>
                  {% trans "Staff management" context "Management section" %}
                </p>
                <ul>
                  {% if perms.account.view_staff %}
                    <li class="{% block menu_staff_class %}{% endblock %}">
                      <a href="{% url 'dashboard:staff-list' %}">
                        {% trans "Staff members" context "Dashboard staff members list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.account.view_group %}
                    <li class="{% block menu_groups_class %}{% endblock %}">
                      <a href="{% url 'dashboard:group-list' %}">
                        {% trans "Groups" context "Dashboard groups list" %}
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </li>
            {% endif %}
            {% if perms.site.edit_settings or perms.shipping.view_shipping or perms.product.view_properties %}
              <li class="side-nav-section">
                <p>
                  {% trans "Configuration"  context "Dashboard configuration" %}
                </p>
                <ul>
                  {% if perms.product.view_properties %}
                    <li class="{% block menu_product_types_class %}{% endblock %}">
                      <a href="{% url 'dashboard:product-type-list' %}">
                        {% trans "Product types" context "Dashboard product types list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.product.view_properties %}
                    <li class="{% block menu_attributes_class %}{% endblock %}">
                      <a href="{% url 'dashboard:product-attributes' %}">
                        {% trans "Attributes" context "Dashboard attributes list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.shipping.view_shipping %}
                    <li class="{% block menu_delivery_class %}{% endblock %}">
                      <a href="{% url 'dashboard:shipping-methods' %}">
                        {% trans "Shipping methods" context "Dashboard shipping methods list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.site.edit_settings %}
                    <li class="{% block menu_settings_class %}{% endblock %}">
                      <a href="{% url 'dashboard:site-index' %}">
                        {% trans "Site settings" context "Dashboard site settings" %}
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </li>
              <li class="side-nav-section" id="version-indicator">
                <p>
                  {% trans "Release:" context "Dashboard software version" %} {% version %}
                </p>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <div class="subheader top-nav">
      <div class="nav-wrapper container">
        {% block breadcrumbs %}
          <ul class="breadcrumbs">
            <li class="visible-s">
              <a href="#">
                {% trans "Home" context "Dashboard homepage" %}
              </a>
            </li>
          </ul>
        {% endblock %}
        {% block header_extra %}{% endblock %}
      </div>
    </div>
    <main class="main">
      <div id="base-modal" class="modal"></div>
      <div id="base-modal-fixed" class="modal modal-fixed-footer"></div>
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>
    <div id="messages-container" data-messages="{% serialize_messages %}"></div>

    <!-- Core Scripts - Include with every page -->
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    {% render_bundle 'vendor' 'js' %}
    {% render_bundle 'dashboard' 'js' %}
    <script src="{% static "versatileimagefield/js/versatileimagefield.js" %}"></script>

    {% block custom_js %}{% endblock %}
  </body>
</html>

python/django/saleor/templates/dashboard/base_modal.html
{% load i18n %}

<form
  role="form" method="post" action="{% block action_url %}#!{% endblock %}"
  class="{% block form_class %}form-async{% endblock %}" novalidate>
  {% comment %}Empty form_class can be used for non-ajax forms with server redirect.{% endcomment %}
  {% csrf_token %}
  <div class="modal-content">
    <div class="row">
      <div class="col s12">
        <h5>
          {% block title %}{% endblock %}
        </h5>
      </div>
    </div>
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close btn-flat waves-effect">
      {% block cancel_action %} {% trans "Cancel" context "Dashboard cancel action" %} {% endblock %}
    </a>
    <button type="submit" class="modal-action btn-flat waves-effect">
      {% block primary_action %}{% endblock %}
    </button>
  </div>
</form>

python/django/saleor/templates/dashboard/base_zero_page.html
<div class="card zero-page">
  <div class="card-content">
    <div class="zero-page__title">
      {% block title %}{% endblock %}
    </div>
    <div class="zero-page__content">{% block content %}{% endblock %}</div>
  </div>
</div>